"""init_db

Revision ID: dc3a880d038d
Revises: 
Create Date: 2024-05-30 14:02:53.951241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'dc3a880d038d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user',
                    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('password', sa.String(), nullable=False),
                    sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('time_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_user'))
                    )
    op.create_table('auth_refresh_token',
                    sa.Column('uuid', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('refresh_token', sa.String(), nullable=False),
                    sa.Column('expires_at', sa.DateTime(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'],
                                            name=op.f('fk_auth_refresh_token_user_id_auth_user'), ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_auth_refresh_token'))
                    )

    superuser = {
        "username": "superuser",
        "password": "superuser",
        "is_admin": True,
    }

    op.bulk_insert("auth_user", [{**superuser}])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_refresh_token')
    op.drop_table('auth_user')
    # ### end Alembic commands ###
