class ErrorCode:
    AUTHENTICATION_REQUIRED = "Authentication required."
    AUTHORIZATION_FAILED = "Authorization failed. User has no access."
    INVALID_TOKEN = "Invalid token."
    INVALID_USERNAME = "Invalid email."
    INVALID_PASSWORD = "Invalid password."
    INVALID_CREDENTIALS = "Invalid credentials."
    INVALID_USERID = "Invalid ID taken."
    FORM_VALIDATION_FAILED = "User form validation failed"
    EMAIL_TAKEN = "Email is already taken."
    REFRESH_TOKEN_NOT_VALID = "Refresh token is not valid."
    REFRESH_TOKEN_REQUIRED = "Refresh token is required either in the body or cookie."
